sudo: false
os: 
  - linux
language: node_js

install: skip
script:
  - false
node_js:
  - '10'

jobs:
  include:
    - name: test
    - name: test2
    - name: test3
    
notifications:
  email: asari.ruby@gmail.com
