language: ruby
dist: xenial
jobs:
  include:
    - stage: test
      script: skip
    - # stage name not required, will continue to use `test`
      script: true
    - stage: deploy
      script: skip
