language: php
install: skip
script: skip

env:
  global:
    - secure: "tCdQWDvceUQ3fEsJegskcfr2VUi6weObuYMEK7DQukqF6YRlKNQ1iJUO5eV3rO2cdDAhDNbnxs33FoG+jnECu8rqtGWHFbFMsvPn8MiA2o90xZ9A7/7d1VSPvfr/hs9nJFqomIrKM2MgN5Q+kROQJKZZMRrDAw0PzHv3KKua/JknYWYlzNxCCTpPM07HyVF8hcxK/kWcYb+l5tXk0nSiXpDzS18eEZ/C+bnnmGEPOnGIoJFihqKH7UKNGeZcj/IjyYfvVYCCfUwbFN9XN/56JbwDpF3ILYzIc0ujbkT+Ocl/3v+JCJJCSWqCAUI5SDrcPVkyY8fAH6V+mH0VXVJ4FZdDHZJuNgY8z7AKbywCUeXh+34CDODZ7NKXvEtp/rOuSABok9l+G7++2mlGlP4Gh4+p8KPvmR6v0FBbm6guSpD50cp4nh0MMvxki4y5J2FjHz8W7z9eJ/i+GmuvS/2tHo07XoKV7L05gigPC9K7JH00HOYGDINdignRh3lrXPPNzs7HOYg38J1QfDnAYK2sXEXvRGNY/mSPyyV7/BuzVL5TLOtKgYPVgJ4//Xj7dID2VDYRHVXLwINGgXyTNIePB5JRdo/XxvdJjjhdN9QHGw2rr4NyI+yQVf6YfqvclQ8lMe/v2GgDzh5nvXmMG+vaABNsJQzl4EBVKK7BlUYXB58="

