language: ruby
dist: focal

install: skip

script:
  - |
    echo building
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "****> linux <****";
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "----> osx <----";
    fi
    echo $SECRET
