language: c
dist: trusty

before_install:
  - rvm use 1.8.7 --install --binary --fuzzy
  - if `ruby -e 'exit(RUBY_VERSION.to_f < 2.7)'`; then
      gem i rubygems-update -v '< 3' && update_rubygems;
      gem install bundler -v '< 2';
    fi

install: skip

script:
  - ruby --version
  - bundle --version
  - bundle install

