sudo: false
os: 
  - linux
language: node_js

install: skip
script: skip
node_js:
  - '10'
  
jobs:
  include:
    - stage: One
      name: job1-1
    - name: job1-2
    - stage: Two
      name: job2-1
    - name: job2-2
